project:
  type: website

website:
  title: "philip's curve"
  navbar:
    collapse: false
    right:
    - icon: github
      href: https://github.com/philip-khor
    - icon: mastodon
      href: https://masto.ai/@pk
    - icon: linkedin
      href: https://www.linkedin.com/in/philip-khor/
  page-footer: 
    right:
      - about.qmd
  search: 
    location: sidebar
  favicon: icon.png
  site-url: www.philipscurve.com
execute:
  freeze: auto

format:
  html:
    theme: 
      light: spacelab
      dark: slate
    # css: styles.css
    toc: true
    
editor: visual

