project:
  type: website
  render:
    - '*.qmd'
    - '/post/2018-*-exploring-ge14-results-with-python*.md'
    - '/post/2018-08-23-visualising-government-expenditure-data-with-ggplot2.Rmd'
    - '/post/2019-05-04-my-first-package-bnmr.md'
    - '/post/2019-06-05-psa-python-ols-and-perfectly-collinear-variables.md'
    - '/post/2019-06-13-file-paths-and-data-science-projects.Rmd'
    - '/post/2019-07-14-link-functions-matter.Rmd'
    - '/post/2019-10-14-charts-can-lie.md'
    - '/post/2020-10-11-why-do-cross-validation/2020-10-11-why-do-cross-validation.Rmd'
    - '/post/2019-06-09-the-australian-gender-wage-gap-interactive-viz.Rmd'
    - '/post/2020-10-24-nested-cross-validation/index.Rmd'
    - '/post/learning-to-sell/index.md'
    - '/post/reflections-on-the-tidyverse/index.md'
    - '/post/wsl/index.md'
    
website:
  title: "philip's curve"
  site-url: https://www.philipscurve.com
  twitter-card: true
  open-graph: true
  navbar:
    collapse: true
    # left: 
    # - about.qmd
  sidebar:
    tools: 
    - icon: github
      href: https://github.com/philip-khor
      rel: me
    - icon: linkedin
      href: https://www.linkedin.com/in/philip-khor/
    - icon: mastodon
      href: https://masto.ai/@pk
      rel: me
    - icon: activity
      href: https://web.brid.gy/r/https://philipscurve.com
      rel: me
  page-footer: 
    left: "Made with [Quarto](https://quarto.org/)."
    right:
      - about.qmd
      - posts.qmd
  search: 
    location: sidebar
  favicon: icon.png
execute:
  freeze: auto

format:
  html:
    theme: 
      light: spacelab
      dark: cyborg
    # css: styles.css
    toc: true
    smooth-scroll: true
    
editor: visual

