project:
  type: website
  render:
    - '*.qmd'
    - '/posts/2018-*-exploring-ge14-results-with-python*.md'
    - '/posts/2019-05-04-my-first-package-bnmr.md'
    - '/posts/2019-06-05-psa-python-ols-and-perfectly-collinear-variables.md'
    - '/posts/2019-06-13-file-paths-and-data-science-projects.Rmd'
    - '/posts/2019-07-14-link-functions-matter.Rmd'
    - '/posts/2019-10-14-charts-can-lie.md'
    - '/posts/2020-10-11-why-do-cross-validation.Rmd'
    - '/posts/2019-06-09-the-australian-gender-wage-gap-interactive-viz.Rmd'
    - '/posts/2020-10-24-nested-cross-validation/index.md'
    
website:
  title: "philip's curve"
  navbar:
    collapse: false
    right:
    - icon: github
      href: https://github.com/philip-khor
    - icon: mastodon
      href: https://masto.ai/@pk
    - icon: linkedin
      href: https://www.linkedin.com/in/philip-khor/
  page-footer: 
    right:
      - about.qmd
  search: 
    location: sidebar
  favicon: icon.png
  # site-url: https://www.philipscurve.com
execute:
  freeze: auto

format:
  html:
    theme: 
      light: spacelab
      dark: slate
    # css: styles.css
    toc: true
    
editor: visual

