---
title: Philip Khor
pagetitle: About
sidebar: false
page-navigation: false
toc: false
about:
  id: hero-heading
  template: solana
  links:
    - icon: mastodon
      text: Mastodon
      href: https://masto.ai/@pk
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/philip-khor/
    - icon: github
      text: Github
      href: https://github.com/philip-khor
    - text: '{{< iconify simple-icons bluesky >}} Bluesky'
      href: https://bsky.app/profile/philipscurve.com
    - icon: file-earmark-person 
      text: CV 
      href: https://raw.githubusercontent.com/philip-khor/cv/main/cv/philip_khor-cv.pdf
---

::: {#hero-heading .h-card}
<a rel="me" class="p-name u-url" href="https://philipscurve.com">Philip Khor</a> is a data scientist in Malaysia with experience in applied microeconometrics, machine learning and technical writing. He occasionally contributes to open-source projects such as the [conda-forge](https://conda-forge.org/) software distribution project. He is package maintainer of the R package [bnmr](https://github.com/philip-khor/bnmr/).
:::

## Experience

**SustenyX** \| Sustainable Finance Consultant \| August 2024 - present

**Penang Institute** \| Visiting Data Scientist, Socioeconomics and Statistics Programme \| January 2023 - present

**CIMB Bank Berhad** \| Manager, Regional Advanced Risk Modelling, Group Risk \| March 2020 - May 2022

**Skymind AI Berhad** \| Technical Writer \| Oct 2019 - Dec 2019

**GRID Inc.** \| Data Scientist Intern \| May 2019 - Aug 2019

**The Center of Applied Data Science** \| Data Scientist Associate \| Jul 2018 - May 2019

**Penang Institute** \| Research Assistant \| Dec 2015 - Jan 2016, Aug 2016 - Jun 2017

## Education

**University of Wollongong** \| Wollongong, NSW\
Bachelor of Commerce (Hons), Economics \| 2017

**University of Wollongong** \| Wollongong, NSW\
Bachelor of Commerce (Dean's Scholar), Economics \| 2014-2016

**Tunku Abdul Rahman University of Management and Technology** \| Tanjung Bungah, Penang\
Diploma in Business Studies, Accounting \| 2012-2014