---
title: "(Individual) tax rebates suck"
description: "One of my pet peeves is to see people advocate for tax rebates when they should know better."
author: "Philip Khor"
date: "2023/07/09"
---

If you're one of the [16.5% of employees who pay taxes in Malaysia](https://theedgemalaysia.com/article/cover-story-budget-2020-top-tax-bracket-raised-30-tin-number-proposed) you may be familiar with one of the many ways by which you can reduce your tax burden: tax reliefs. From purchases of computers to EPF contributions, there's so many incentives that the government provides for you to save money, or even get some cash back in the process.

But wait a minute, you say. "I'm part of the 16%? The median income in Malaysia was RM5,873 a month in 2019[^1], and I'm barely there." But well, most of you aren't your own household. And if you're a single-earner household, your median income turns out to be just RM2,988 (2019), well below the taxable threshold of around RM3,000 a month. As of 2021, the Salaries and Wages Report, which provides more frequent updates on wage trends, indicates a median income of RM2,250 in 2021.

[^1]: From the Household Income Survey, which is the source for all things B40/M40/T20.

So yeah, if you're familiar with [Borang BE](https://www.hasil.gov.my/media/gf1dooov/form_be2022_2.pdf) pat yourself on the back. You're T20, you've made it as part of the socioeconomic elite.

Tax rebates are a great way for the government to claim to 'fix' problems without actually putting their money where their mouth is. There's no real expense, just revenue forgone. But in truth, like a reverse Robin Hood, tax rebates steal from the poor to subsidise tax bills for the rich. So when a bunch of experts suggested [in the media](https://www.thestar.com.my/news/nation/2023/07/07/ensuring-a-healthy-nest-egg) that tax rebates be used to encourage people to top up their EPF savings, I was rather unhappy.

To see why, let's take a middle-of-the-road employee ('Person A') from a T20 household. In 2019, the median income per capita in a T20 household was RM3,854, or RM 46,248 a year[^2]. For comparison, let's take an individual ('Person B') that earns double that, say RM92,496. For the [year of assessment 2022]( https://www.hasil.gov.my/en/individual/individual-life-cycle/how-to-declare-income/tax-rate/), Person A falls under the 8% tax bracket, whereas Person B falls under the 21% tax bracket. Ignoring all applicable tax reliefs, their tax payable would be as follows:

[^2]: See also <http://web.usm.my/km/30(2)2012/KM%2030(2)%20ART%202%20(27-43).pdf>

|          |               |       |           |
|----------|---------------|-------|-----------|
| Person A | First 35,000  | 600   |           |
|          | 11,248 \@ 8%  | 900   | **1,500** |
| Person B | First 70,000  | 4,400 |           |
|          | 22,496 \@ 21% | 4,724 | **9,124** |

Now suppose that both Person A and B enjoy RM1,000 tax relief on top of the standard RM9,000 tax relief (for existing? idk). This reduces chargable income for each of these persons by RM10,000. However, for Person A, chargable income reduces by 800, while for Person B chargable income reduces by RM2,100. This means the government has forgone 2.6 times more tax revenue for the richer Person B than for Person A, and makes tax deductions highly regressive.

Perhaps you object: Person B's income means he contributes more to society, so he deserves additional relief proportionate to his contribution. Even by that logic, the government has forgone proportionately more revenue than Person B has earned.

Not to mention that the tax relief system is the bane of ratepayers' existence: you are required to keep records for several years. Some of us approach the tax authorities for voluntary audits in fear of getting in trouble some point in the future if we've misunderstood the tax code.

Now, there may be a place for tax relief if the intention is to incentivise the rich to do certain pro-social things, for instance engage in risky investments to spur innovation, or even to purchase insurance, where their purchase of insurance could diversify risk pools and contribute to lower premiums. But it would be a lot more equitable to subsidise these behaviours directly. Insurance vouchers, for instance. Or topping up EPF contributions to a minimum, in the style of a [negative income tax](https://mitsloan.mit.edu/ideas-made-to-matter/negative-income-tax-explained).

If we expanded relief for voluntary contribution to the EPF, only the well-off and financially sound can afford to contribute voluntarily to the EPF at an amount significant enough to make a dent on their tax bill[^3]. Not to lose sight of the fact that while we lobby the government to lower our tax bills, the median savings of EPF members has halved to [RM8,100 in 2022 from RM16,600 pre-Covid](https://www.bernama.com/en/business/news.php?id=2165052).

[^3]: Consider also that the EPF's own analysis has characterised the large disparity between small and large depositors in the system as a problem. <https://www.kwsp.gov.my/documents/20126/ddae99a2-bddd-4aee-4fbb-f85b1b3eddbf>

We need a real conversation about how to fund social security moving forward, lest retirement means poverty for the aging masses.

::: {.callout-note appearance="simple"}
## Disclaimer

This article represents my own opinions and do not represent the opinions of my employer. I am not a tax professional and no part of this article should be taken as tax advice of any kind.
:::
